"""create highscores table

Revision ID: 198bbca5a970
Revises: 
Create Date: 2024-05-18 21:03:46.882362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198bbca5a970'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highscores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('highscore_datetime', sa.DateTime(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_score', sa.Integer(), nullable=False),
    sa.Column('room_socket_id', sa.UUID(), nullable=False),
    sa.Column('ai_bot_type', sa.String(), nullable=False),
    sa.Column('kinde_uuid', sa.UUID(), nullable=False),
    sa.Column('profile_picture', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highscores')
    # ### end Alembic commands ###
